kind: Secret
apiVersion: v1
metadata:
  name: cluster-kubernetes.default.svc-3396314289
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
  annotations:
    managed-by: argocd.argoproj.io
data:
  config: eyJ0bHNDbGllbnRDb25maWciOnsiaW5zZWN1cmUiOmZhbHNlfX0=
  name: aW4tY2x1c3Rlci1sb2NhbA==
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj
type: Opaque