---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-monitoring-appset
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster-local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-openshift-monitoring'
    spec:
      destination:
        namespace: openshift-monitoring
        server: '{{url}}'
      project: default
      source:
        path: manifests-cluster/openshift-monitoring
        repoURL: https://github.com/redhatryan/gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
