---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-config-appset
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-openshift-config'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/redhatryan/gitops'
        path: manifests-cluster/openshift-config
        targetRevision: HEAD
      destination:
        namespace: openshift-config
        server: '{{url}}'
      syncPolicy:
        automated:
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
