---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openshift-pipelines-appset
  namespace: openshift-gitops
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-openshift-pipelines'
    spec:
      destination:
        namespace: openshift-operators
        server: '{{server}}'
      project: default
      source:
        path: manifests-cluster/openshift-pipelines-operator/overlays/latest
        repoURL: https://github.com/redhatryan/gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
