---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-owatanna
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        values:
          revision: HEAD 
      - cluster: test
        url: https://kubernetes.default.svc
        values:
          revision: test
      - cluster: prod
        url: https://kubernetes.default.svc
        values:
          revision: stable
  template:
    metadata:
      name: 'hello-{{cluster}}'
    spec:
      source:
        repoURL: 'https://github.com/redhatryan/animated-bassoon'
        targetRevision: '{{values.revision}}'
        path: 'app/overlay/{{cluster}}'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'hello-houston-{{cluster}}'
